### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by remixxx31** [Pixilib/GaelO_Flow_Frontend#1]
- [x] Charte graphique
- [x] Finalisation de la maquette
- [ ] Intégration de composants Gaelo_UI

**Comment by SophieLab** [comment]
**Finalisation Maquettes Fima :**
- [ ] Design SignUp 1 Page 
- [ ] Design SignUp 2 Page
- [ ] Design SignIn  Page
- [ ] Design Login Page
- [ ] Lost Password


![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/9880ca83-a20e-4ad0-aa74-3d377f9cdf66)
