### ISSUE TITLE
[Banner] [SideBar] Problem superposition with Banner and SideBar

### ISSUE THREAD

**Issue by SophieLab** [Pixilib/GaelO_Flow_Frontend#186]
![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/b65f8e85-45b9-4e1f-beb9-516196258e9a)

**Comment by remixxx31** [comment]
A voir avec l'ombre retirée , si le problème est réglé @SophieLab, sinon je vois pa strop comment le régler!
