### ISSUE TITLE
[Users] Rendre visible la barre de navigation dès le chargement de la page sans nécessiter de passer la souris sur la table

### ISSUE THREAD

**Issue by SophieLab** [Pixilib/GaelO_Flow_Frontend#232]
![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/8f2a97ab-1252-4c9a-bb0c-5b39c5a9431b)

![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/5059df31-be0d-4a7a-8976-24228e73720f)

Actuellement, pour afficher la barre de navigation, l'utilisateur doit passer la souris sur le tableau. Cependant, il est essentiel que l'utilisateur puisse voir immédiatement qu'il peut naviguer dans le tableau sans avoir à deviner cette fonctionnalité.

- [ ]  Rendre la barre de navigation visible en permanence.
- [x]   Assurer que la barre de navigation ne gêne pas la lecture des données dans le tableau.

**Comment by remixxx31** [comment]
@SophieLab  , Je n comprends pas elle est visible en permanence pour moi .
Tu m'expliqueras demain plus en détail, je vois pas trop ou est le problème.
