### ISSUE TITLE
[PatientEditModal] : Implement Patient Edit Form

### ISSUE THREAD

**Issue by remixxx31** [Pixilib/GaelO_Flow_Frontend#267]
### Checklist
- [x] Create a `PatientEditModal` component.
- [x] Include the following fields in the form:
  - Patient ID (readonly)
  - Patient Name
  - Patient Birth Date
  - Patient Sex
- [x] Add a Save button to submit the form.
- [x] Add a Cancel button to close the modal without saving.
- [x] Implement form submission logic.
- [x] Style the modal usi
![Screenshot from 2024-07-12 00-10-54](https://github.com/user-attachments/assets/e4535100-a11b-4e92-9bcc-ccdab39c7e49)

### Questions
1. What is the API endpoint for updating patient details?
- [ ] Need to this API #277 
2. Should there be any additional fields or buttons?

**Comment by remixxx31** [comment]
J'ai trouvé cette API patients/id/modify, je pense que c'est la bonne ?
Après je dois appeller l'api jobs dans la foulée avec l'ID de la  response de l'APi précèdente exemple:https://otjs.ddns.net/api/jobs/0b2db275-3492-444b-8cc9-a4cc27368c4f?
Ou juste invalider la clé jobs ?
On peut supprimmer n'importe quel champ de type PatientMainDIcomTags à part ID ?

Voici le type de Payload:
{
    "Replace": {
        "PatientID": "\tef28989e-c4bf-4360-8242-e0287ca59fb7"
    },
    "Remove": [
        "PatientSex"
    ],
    "RemovePrivateTags": true,
    "Force": true,
    "Synchronous": false,
    "KeepSource": false
}

Il y a un truc que je comprends pas , c'est qu'on ait obligé de spécifier le patient ID qui ne doit pas être vide , ni le même qu'avant, par contre si on copie-colle l'ancien ID ça fonctionne quand-même ?

@salimkanoun

**Comment by salimkanoun** [comment]
Yes c'est la bonne api
Oui faut appeler job avec l id, mais réutilise le composant de suivi de job que t a fait pour le retrieve, la logique est la même tu a deja implémenté tout ca

**Comment by salimkanoun** [comment]
Non y a des tag dicom qui ne peuvent pas être supprimés, je pense qu'on a géré ça dans Orthanc tools js tu dois pouvoir les retrouver dans le code (ça dépend du niveau d édition patient / study ou séries)

**Comment by salimkanoun** [comment]
RemovePrivateTags": true, => mettre false
"KeepSource": false => ce boolean dépend de l'interface graphique tu met une case à cocher pour savoir si tu keep le dicom original ou pas

**Comment by remixxx31** [comment]
Coucou Salim je t'ai envoyé un message dans Discord.
J'ai un soucis avec l'API de Modify Patient, je ne comprends vraiment pas ce qui me manque!
[https://discord.com/channels/@me/1059479477870141481/1263494694357438545](url)

@salimkanoun

**Comment by remixxx31** [comment]
Est-ce que ce type de formulaire va bien pour l'edition de Patient ?
Je n'ai pas mis de newValue j'ai mis directement la valeur à editer ça va ou pas ?

![Image](https://github.com/user-attachments/assets/733b98b1-a834-4abb-9aa9-e3e18d0a25f4)

@salimkanoun

**Comment by remixxx31** [comment]
> Est-ce que ce type de formulaire va bien pour l'edition de Patient ? Je n'ai pas mis de newValue j'ai mis directement la valeur à editer ça va ou pas ?
> 
> ![Image](https://private-user-images.githubusercontent.com/69733620/350162547-733b98b1-a834-4abb-9aa9-e3e18d0a25f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDExODIsIm5iZiI6MTcyMTM0MDg4MiwicGF0aCI6Ii82OTczMzYyMC8zNTAxNjI1NDctNzMzYjk4YjEtYTgzNC00YWJiLTlhYTktZTNlMThkMGEyNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIyMTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODBhYzJmZGM1YTNjZTQzMzk0ZjQ3MGRhYjkyZjdkYzQzMjAwMzJjYjlhMGViNWRlMDMyMzA3MTZjMTExMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wy6QxXMcOzYBCgT1SX2HlvWwOVGOLy03ggwenp0dBRg)
> 
> [@salimkanoun](https://github.com/salimkanoun)

Est-ce qu'il faut que je retire les champs si ils ont nulls?

**Comment by remixxx31** [comment]
> > Est-ce que ce type de formulaire va bien pour l'edition de Patient ? Je n'ai pas mis de newValue j'ai mis directement la valeur à editer ça va ou pas ?
> > ![Image](https://private-user-images.githubusercontent.com/69733620/350162547-733b98b1-a834-4abb-9aa9-e3e18d0a25f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDExODIsIm5iZiI6MTcyMTM0MDg4MiwicGF0aCI6Ii82OTczMzYyMC8zNTAxNjI1NDctNzMzYjk4YjEtYTgzNC00YWJiLTlhYTktZTNlMThkMGEyNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIyMTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODBhYzJmZGM1YTNjZTQzMzk0ZjQ3MGRhYjkyZjdkYzQzMjAwMzJjYjlhMGViNWRlMDMyMzA3MTZjMTExMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wy6QxXMcOzYBCgT1SX2HlvWwOVGOLy03ggwenp0dBRg)
> > [@salimkanoun](https://github.com/salimkanoun)
> 
> Est-ce qu'il faut que je retire les champs si ils ont nulls?

La valeur PatienId ne doit pas être null , on est d'accord si une quelconque modification est soumis par le formulaire le patientId doit être différent ?

**Comment by salimkanoun** [comment]
Non le patient id peut rester le même aussi, il doit avoir une valeur mais test pas obligé de la changer.

Le reste me semble bon, tu a des composants similaires a faire pour l'édition des studies et series, c'est les items qui changent

**Comment by salimkanoun** [comment]
Les champ delete tu les grise comme ça c'est réversible

**Comment by remixxx31** [comment]
> Les champ delete tu les grise comme ça c'est réversible

Quand je clique sur la poubelle tu veux que l'input devienne disable , c'est ça ?

**Comment by salimkanoun** [comment]
> > Les champ delete tu les grise comme ça c'est réversible
> 
> Quand je clique sur la poubelle tu veux que l'input devienne disable , c'est ça ?

yes
