### ISSUE TITLE
Fix: API Modify Patient

### ISSUE THREAD

**Issue by remixxx31** [Pixilib/GaelO_Flow_Frontend#277]
API in Back-end Gaelo-Backend doesn't exist ?
Do you need to create one ?

[https://discord.com/channels/@me/1059479477870141481/1263494694357438545](url)

**Comment by salimkanoun** [comment]
Yes en effet je viens de le faire ici : https://github.com/Pixilib/GaelO_Flow_Backend/commit/32fc97fa3c6fe429a7c7aae97962bb5d2220acaf
