### ISSUE TITLE
FormJobsActions ? utilité ? 

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Frontend#287]
FormJobsActions supprimer, pour tout ce qui est content on ne donne pas accès a la modif des jobs (réservé aux admins)

**Comment by remixxx31** [comment]
@salimkanoun  
 En fait FormJobsAction c'est un composant qui va afficher tantôt les boutons de l'EditModal et quand un Job est lancé il affiche le ProgressJObs.
En soit je peux directement implémenter ça dans chaque form mais ça dupplique du code

**Comment by salimkanoun** [comment]
Ça doit pas en dupliquer beaucoup t a juste un state a gérer si y a un job id ou pas
