### ISSUE TITLE
Rename svg bg img with explicit name

### ISSUE THREAD

**Issue by remixxx31** [Pixilib/GaelO_Flow_Frontend#29]
Rename with explicit name in Figma and React  with the same name:

![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/69733620/84d1b79d-bc73-4260-ad84-9b93d8731119)

exemple: VisualHome1 in Figma and react

**Comment by SophieLab** [comment]
- [ ] Rename svg bg with explicit name **for Welcome Page (Done)** 

![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/d7525ae2-cb35-4cef-91d5-259519996347)
