### ISSUE TITLE
Button on SignINFOrm and SignUpForm doesn't have the same color

### ISSUE THREAD

**Issue by remixxx31** [Pixilib/GaelO_Flow_Frontend#41]

**Comment by SophieLab** [comment]
Je l'ai modifié hier pourtant ..

<Button
              color={Colors.primary}
              onClick={() => onRegister()}
              className="w-60"
              >
              Create your account
              <ChevronRight />
            </Button>
          </div>
        </div>
      </div>
    );
  };

  <Button
            color={Colors.primary}
            onClick={() => onLogin(username, password)}
            disabled={username.length === 0 || password.length === 0}
          >
            Connect
            <ChevronRight />
          </Button>
        </div>
      </div>
    </div>
  );
};
