### ISSUE TITLE
[Side Bar] Integrate the new Side Bar

### ISSUE THREAD

**Issue by SophieLab** [Pixilib/GaelO_Flow_Frontend#97]
- [x] Integrate the new Side Bar according to the Design (**hovered element = #8C8BD3**, **  Active element (when the user clicks on it: **Primary hover**)**

![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/c47efecd-a4f8-4b1c-aaeb-f3edf5294d62) ![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/5618caeb-d26a-498c-8808-a20d5ee77722)

- [x]  Be careful when creating the sidebar : pay attention to the minimum height of the sidebar To avoid overlapping divs, it's necessary to ensure there is a minimum and maximum height and **to implement overflow with a scrollbar system.**
![Image](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/48235bb3-2eb4-414a-8cc7-882a0bc30486)

**Comment by SophieLab** [comment]
![Capture d’écran du 2024-02-21 13-59-49](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/8360e4cc-e1e1-49f5-99ca-8da5dbf3b8c6)
![Capture d’écran du 2024-02-21 13-59-15](https://github.com/Pixilib/GaelO_Flow_Frontend/assets/152176619/15eaaaac-b00c-4a19-bc3b-dd1a1f31c27e) 
Les boutons principaux doivent aussi avoir le même arrondi  et la même tailles que les autres ( ci joint les captures)

**Comment by remixxx31** [comment]
Ok ça marche

**Comment by remixxx31** [comment]
Par contre pour les buttons tu parle du logo Home ?
